### ISSUE TITLE
Documentation, please

### ISSUE THREAD

**Issue by reteps** [ZekeSnider/Jared#10]
I really like the program you've made here. I do have some suggestions, though.

+ Please add a `writing a plugin` wiki, as I don't know swift so It might be hard for my idea to become a reality
+ Please add a `config.json` file, to turn on/off certain `Jared` functionality
+ Please list the things `Jared` can do in your README

**Comment by ZekeSnider** [comment]
Thanks for your interest in this project! I will take a look at adding these features/documentation. I haven't worked much on it recently but I will try to address these as I work on the Swift 3 branch.

**Comment by reteps** [comment]
Thank you for all your help.My own project, Otto is in progress written in golang. I hope you don't mind if I borrow some of your code, as long as I credit you. Cheers!

**Comment by ZekeSnider** [comment]
No Problem, glad to help out. Jared is licensed under the Apache 2.0 License, so you are free to do whatever you like with the source as long as you abide by the terms of that license (include copy of license, state changes made, etc). See here: [https://github.com/ZekeSnider/Jared/blob/master/LICENSE.txt](https://github.com/ZekeSnider/Jared/blob/master/LICENSE.txt)

**Comment by ZekeSnider** [comment]
Closing the issue as I've addressed the three items here:
• Added plugin development info to the readme
• config.json file has been added
• command list added to the readme
