### ISSUE TITLE
Who sent that message? [feature]

### ISSUE THREAD

**Issue by reteps** [ZekeSnider/Jared#11]
Please add a way to see which number / email a text came from.

**Comment by ZekeSnider** [comment]
The Room class already contains the buddy's name if they are in your contacts.app. I think it would contain their phone/email if they are not in your contacts. Are you looking for something more than this?

**Comment by reteps** [comment]
That's perfect. Where are the response strings for Jared? Are they zipped up in framework

**Comment by ZekeSnider** [comment]
The Jared API is exposed through a framework, or you can modify Jared directly if you don't want the modularity of plugins. Take a look at SampleModule to see what a module looks like. I will work on adding better documentation in the next update.
