### ISSUE TITLE
Just the receive / send parts please

### ISSUE THREAD

**Issue by reteps** [ZekeSnider/Jared#12]
Is there a way I can just use the send / receive sections of Jared? I want to write my own program, but I can't figure out how to modify `send group chat.scpt` and `Jared.scpt` to output to a file or program.

**Comment by ZekeSnider** [comment]
You mean you want to automate sending iMessages through Applescript without using a Jared plugin? Take a look at Jared/SendText.scpt and Jared/SendImage.scpt. You will need the internal ID of the group to send a group chat. If it is a 1-1 chat there is another syntax you can use with the email/phone number of the contact.

**Comment by reteps** [comment]
how can I get the internal ID of the group? Thanks!

**Comment by ZekeSnider** [comment]
You can pull it from the messages.app sqlite database, or you can use an applescript event listener, then copy from on received message event, which is what Jared does.

**Comment by reteps** [comment]
is it the `guid`? like this format: `iMessage;+;chat27695X48872X83199`?

**Comment by ZekeSnider** [comment]
Yes, that looks like the correct format.
