### ISSUE TITLE
Jared (Not Found) in Messages AppleScript dropdown.

### ISSUE THREAD

**Issue by Chewsterchew** [ZekeSnider/Jared#15]
I'm probably doing something very wrong but 
![image](https://user-images.githubusercontent.com/8278263/27971638-13f0bfea-6319-11e7-8ff3-26d5ad03b8bf.png)

I'm currently using macOS Sierra (10.12.5)

**Comment by ZekeSnider** [comment]
Does that happen when you click Jared.scpt on that list? Have you verified that the script is still in the scripts folder?

**Comment by Chewsterchew** [comment]
If I click Jared.scpt and switch tabs or reopen the window, it simply shows none.
I have the script folder open and it still there

**Comment by ZekeSnider** [comment]
Huh, I've never encountered that before. Have you tried recopying the file, restarting the computer, and selecting? Do any of the other built-in scripts in there work?

**Comment by Chewsterchew** [comment]
All the other built-in scripts seem to work, am I only supposed to copy the script?

**Comment by ZekeSnider** [comment]
Can you try

1. Make sure JaredUI.app is running
2. Open the script located in the imessage script folder in script editor
3. Build it, if it asks where JaredUI app is, point to it
4. Set handler in messages.app again

And see if that fixes anything?

**Comment by Chewsterchew** [comment]
1) I opened the JaredUI.app (didn't realise it needed to be)
2) I opened the Jared.scpt
3) I clicked the "play" (run) and the hammer (which I assumed to be build) but nothing showed up.
4) Same error, even after restarting Messages.

**Comment by alcatrazpuller** [comment]
You dont need the script itself to be open or running in Script Editor, it only has to be loaded into the Messages preferences. @ZekeSnider just wanted to make sure the script you had actually built (had no errors).

So make sure JaredUI.app is running AND Jared.scpt is selected in Messages' Applescript handler. If it still won't load in, you could try it again as a different user.

**Comment by ZekeSnider** [comment]
@Chewsterchew Were you able to find a solution to the issue? I'm going to close the issue if it's been resolved.

**Comment by Chewsterchew** [comment]
I've just given up on it, I'll try again in the future

**Comment by ZekeSnider** [comment]
Ok, if you have issues in the future please open another issue.
