### ISSUE TITLE
MacOS High Sierra missing apple script handler from messages.app

### ISSUE THREAD

**Issue by mezeipetister** [ZekeSnider/Jared#20]
Hi Guys,

It's Peter Mezei, and just wanted to try out your Bot, but stack with messages.app.
It looks like Apple has recently removed the possibility to set custom script handling functionality from its apps - like from messages app.

Do you have any idea how to solve this issue?

**Comment by ZekeSnider** [comment]
Hi,

Thanks for letting me know. I hadn't noticed this before, but apparently (much to my dismay) Apple quietly removed this in 10.13.4. [More info here](https://apple.stackexchange.com/questions/318230/did-apple-remove-the-applescript-handler-option-in-macos-high-sierra).

I tried editing the plist directly (`~/Library/Containers/com.apple.soagent/Data/Library/Preferences/com.apple.messageshelper.AlertsController.plist` and `~/Library/Preferences/com.apple.iChat.plist`) to see if it was just removed from the UI, but I haven't had any luck so far. Unfortunately, if there's no workaround using the plists, this may be the end of the road for Jared. It'll still work on 10.13.3 and earlier, but that just makes it more inconvenient to run.

**Comment by mezeipetister** [comment]
But for now, as I see there is no way to create chatbot for iMessage? I am looking for any possible solution to create a custom chatbot for iMessage.

**Comment by ZekeSnider** [comment]
There is no way with this functionality removed. I don't think anybody has managed to reverse engineer the private iMessage APIs. If you need an iMessage chatbot working, easiest way would be to downgrade your macOS version currently.

**Comment by mezeipetister** [comment]
Thank you!

**Comment by mezeipetister** [comment]
I have found an ugly way to solve it. Access messages through its sqlite database.
In this way I can write a workaround that runs as a while true loop, watching the new messages and once its the right one it can reply to message.

SQLite part:
set result to do shell script (["sqlite3 -line ~/Library/Messages/chat.db ", ¬
				"'SELECT MAX(date) lastMessageDate, h.id, text, m.ROWID ", ¬
				"FROM message m INNER JOIN handle h ON h.ROWID=m.handle_id ", ¬
				"WHERE 'm.ROWID' > " & rowIdNow & " GROUP BY h.ROWID' | egrep -io -e '\\w+ = .+'"] as text)

**Comment by ZekeSnider** [comment]
Thanks for the idea, that looks like it'll be a serviceable workaround. Not pretty, but I don't think there's another option... I've looked at the db before but hadn't thought of watching it on loop.

I'm going to try to get Jared updated using this method, will update this issue as it progresses.

**Comment by ZekeSnider** [comment]
Very late response here, but I've gotten the database querying working on a branch.It is running on Mojave. I am working on testing and making sure everything works, as well as adding a few features to the next version of Jared.

**Comment by otisdog8** [comment]
How do you make sure the database is up to date? It takes chat.db about 15 minutes to update on my computer.

**Comment by ZekeSnider** [comment]
Really? I’ve been testing on my machine and it’s always instant (I’ve been querying on a 5s interval). That is, unless another process is holding a lock on the db, it which case it won’t update until the lock is released. I’d be curious about why it is so infrequent for you.

**Comment by otisdog8** [comment]
Yeah it turns out I had it pointing at the wrong file. I had created a version of it outside of ~/Library/Messages to get around the full disk access restriction, and I had the file pointing at that. Might I ask how you query the database for updates?

**Comment by ZekeSnider** [comment]
That makes sense, I think the sqlite API reads from the shm and wal files as well. Here's how I'm querying the database: https://github.com/ZekeSnider/Jared/blob/xcode10/JaredUI/sqlitetest.swift (it does require full disk access)

**Comment by ZekeSnider** [comment]
Closing this issue as the database functionality has been merged to master. Feel free to open another issue if needed.
