### ISSUE TITLE
Several Commands Broken

### ISSUE THREAD

**Issue by gardinermichael** [ZekeSnider/Jared#27]
Hey there! Love the idea. I'm having a couple issues running some basic commands.

```
/schedule,add,1,week,5,message
```
returns:

```
Send interval type must be a valid input (hour, day, week, month).
```
Secondly, running:

```
/help,schedule
```
Returns nothing

**Comment by ZekeSnider** [comment]
Hi, apologies for the very late response. This is bad documentation, I think the issue is `week` must be capitalized to `Week` in your command. And for the `/help` issue it's a bit counter intuitive, buit you need to send `/help,/schedule`

**Comment by ZekeSnider** [comment]
Closing this, feel free to reopen if you’re still having issues.
