### ISSUE TITLE
Create routes that use external APIs for easier Jared extension

### ISSUE THREAD

**Issue by kjb085** [ZekeSnider/Jared#29]
Would be really awesome if there was a section in the config file that a user could add in custom commands and that would then map those commands to an API end point. That end point would then accept the command, wait for the response from the API (with a reasonable timeout of course), and then return the output from the API back to the user. 

**Example**

Here's my idea for what an updated config file would look like based off of what is currently in the sample config.

```json
{
    "routes": {
        "/ping": {
            "disabled": true
        },
        "/reverse": {
            "endpoint": "http://localhost:8080/reverse"
        }
}
```

The result of this would provide a command allowing the user to then message an Apple ID running Jared with following:

> /reverse testing 123

Jared would then make a get request to `http://localhost:8080/foo?input=testing%20123` (the get param can be whatever makes the most sense or even have it be configurable from the config). The api endpoint would then respond to Jared with "321 gnitset" (assuming the server running on 8080 was working appropriately and its purpose was just to reverse any string which was past to it, if that wasn't apparent) which would be directly passed back to the user.

Also, without digging into the code, I'm not sure if makes sense to include everything under `routes` like I've outlined or if a new config key (ex: `api_routes`) would make more sense, but obviously this is a more of a technical aspect that the core functionality is not concerned with.

**Comment by ZekeSnider** [comment]
I like the idea! I think it makes sense for it to have some new market in the routes config file. 

Were you thinking that it should expect the endpoint to conform to some format, or just proxy the result directly? I'm thinking it would at least need to check the MIME type of the response, so that it wouldn't spit back a HTML blob for example.

**Comment by kjb085** [comment]
Ah yea, was thinking that the end point would return some kind of simple json object. Keys of success: bool and message: string. Maybe if success is false a string of error for logging purposes too?
