### ISSUE TITLE
No REST API available

### ISSUE THREAD

**Issue by eliluong** [ZekeSnider/Jared#32]
Hi, I've installed this on 10.15 Catalina. It seems to run and intercept messages properly. There does not seem to be a button to enable REST API in the GUI. Is there a trick to enabling it? Thanks.

**Comment by ZekeSnider** [comment]
Hi, I haven’t released a prebuilt binary that includes the REST API yet, so you’ll need to build and run from source until I do that.

**Comment by ZekeSnider** [comment]
1.4 was just released as a prebuilt binary. Please re-open this if you're still having issues on that version.
