### ISSUE TITLE
Fallback config.json content is invalid

### ISSUE THREAD

**Issue by MPM10223** [ZekeSnider/Jared#46]
If you don't have a config.json file, one is created for you with default content from the Bundle (below):

```json
        "routes": {
        },
    "webhooks": [
    ],
    "webserver": {
        "port": 3005
    }
}
```

However, this default content contains a typo, making it invalid: **the `webserver` entry should instead be `webServer` with a capital `S`**

The workaround is to manually modify this file after creation, or make sure to seed your application with the contents in `config-sample.json` in the documentation (which _does_ have the capital `S`)

**Comment by ZekeSnider** [comment]
Thanks for catching this! I just cut a PR to fix this.

**Comment by ZekeSnider** [comment]
Fixed in this release: https://github.com/ZekeSnider/Jared/releases/tag/1.5.1
