### ISSUE TITLE
Jared stops responding to messages after ending screen share on server.

### ISSUE THREAD

**Issue by ES15643** [ZekeSnider/Jared#49]
The chatbot will respond to messages when screen sharing with server, but once screen sharing has ended, it fails to respond to messages. Does Jared need to have an active sign in ( besides the message app ) to work?

**Comment by ZekeSnider** [comment]
The mac needs to be active and awake to run the server. Is your mac going to sleep after disconnecting from screen share?

**Comment by ZekeSnider** [comment]
I'm gonna close this, but feel free to reopen if this is still an issue for you.
