### ISSUE TITLE
Jared cannot check send permissions because Me....

### ISSUE THREAD

**Issue by russellaugust** [ZekeSnider/Jared#52]
I'm getting this error / warning and I can't seem to get around it.  If I click RECHECK, Jared freezes up and Messages goes into some kinda lockdown.  

<img width="670" alt="Screen Shot 2021-07-25 at 7 44 33 PM" src="https://user-images.githubusercontent.com/1045096/126926131-04e7cdf8-09fc-41a1-9855-c4f490820b86.png">

**Comment by russellaugust** [comment]
I am on the newest Big Sur

**Comment by ZekeSnider** [comment]
Hey, I think this might be related #50 which was just merged. I'll try to reproduce and see if it's resolved with a new build

**Comment by ZekeSnider** [comment]
@russellaugust Could you try again with the [latest release](https://github.com/ZekeSnider/Jared/releases/tag/1.5.2) and let me know if that works?

**Comment by russellaugust** [comment]
ah sorry, didn't get notified of this.  I'll check now

**Comment by russellaugust** [comment]
Success!  Correctly requested access to the OS and is now connected.
