### ISSUE TITLE
Jared won't post to webhook

### ISSUE THREAD

**Issue by andresmaraone** [ZekeSnider/Jared#53]
Setup my webhook in the configuration file, but Jared won't post to it. 

Config File is setup as follows:
`{
    "routes": {
    },
    "webhooks": [
    {
      "url": "https://webhook.site/abcd"
    }
  ],
    "webServer": {
        "port": 3005
    }
}`

**Comment by ZekeSnider** [comment]
Hey @andresmaraone I just tried running this on my machine with that config (just substituted the url), and it seems to be working.  I just published 1.5.2 which has some more log statements, could you give that a try and let me know if the logs reveal anything? https://github.com/ZekeSnider/Jared/releases/tag/1.5.2

I'm not sure what the issue would be, if it's not a problem with parsing the config file. So hopefully the logs tell us something. Next debugging step I would recommend is setting some breakpoints in the xcode debugger in `Jared/WebhookManager.swift`.

**Comment by mikeoneone** [comment]
I'm having this same issue. I have defined my webhook and it is never fired. I am looking at the system log and I don't see any messages from Jared. It's like the app doesn't know the webhook is configured. 
My config.json file is as follows:

{ "routes": { }, "webhooks": [ { "url": "https://webhook.site/06a1a542-daee-451e-9e3e-3c30a769dfa9" } ], "webServer": { "port": 3005 } }
