### ISSUE TITLE
send to groups over REST API?

### ISSUE THREAD

**Issue by jclin22009** [ZekeSnider/Jared#58]
Hi,

I've been playing with Jared, and it's completely awesome! One issue I'm running into is sending messages to groups. My request is formatted as:
`r = requests.post("http://localhost:3000/message",json={"body": {"message": message}, "recipient": {"handle": recipient_id}})`
And I just set `recipient_id` to the iMessage id of the group (i.e. `iMessage;+;chat238923983289`). However, this does not seem to work. Would you recommend adding a field in the API request for participants, or using the webhook (I notice there is an example for group messaging on the webhooks section). Thank you!

**Comment by ZekeSnider** [comment]
Hi, the API should function as you're describing, but I think there's a bug in the handle comparison logic. The API should parse out if it's a group based on the handle format. If you're able to build from source could you try out this branch and let me know if that fixes it?

https://github.com/ZekeSnider/Jared/compare/zeke/fix-handle-comparison?expand=1

**Comment by jclin22009** [comment]
I think it works, thank you!

**Comment by ZekeSnider** [comment]
Awesome, merged that into master!

**Comment by simonwarchol** [comment]
Do you mind creating a new release?

**Comment by ZekeSnider** [comment]
@simonwarchol yep, done! https://github.com/ZekeSnider/Jared/releases/tag/v1.5.4

**Comment by saikarthikp9** [comment]
How do you find the iMessage ID of a group?

**Comment by simonwarchol** [comment]
`/barf` should give you the info you need :)

**Comment by saikarthikp9** [comment]
I just don't want to send the /bark in that group chat. Is there another way?

**Comment by jclin22009** [comment]
Another way is to enable the REST API and monitor the incoming chat messages (if someone sends something to the group) and copy the ID from there.

**Comment by saikarthikp9** [comment]
Where exactly do I "monitor" this? Are logs stored somewhere? I've enabled REST APIs.

**Comment by ZekeSnider** [comment]
Check out the [webhooks documentation](https://github.com/ZekeSnider/Jared/blob/master/Documentation/webhooks.md), you can use a site like [webhook.site](https://webhook.site) to easily monitor requests. That will show you the content of messages including the group chat guid.
