### ISSUE TITLE
REST API unable to send to Group Chat

### ISSUE THREAD

**Issue by kvongole328** [ZekeSnider/Jared#67]
Am trying to send a message via the REST API to an iMessage Group chat and it's not sending - even though a 200 is being returned. 

Code: `  response = requests.post(url, json=data)` where the json has `"handle": "iMessage;-;chat636774097307250120"`  
I retrieved that handle from the webhook where I monitored inbound messages from that groupchat.

Screengrab of terminal returning a 200 sent below. Interestingly, the webhook monitoring Jared is not receiving any data at this point. 

![Screen Shot 2022-12-06 at 1 04 01 PM](https://user-images.githubusercontent.com/33531680/205999392-877cbcb0-0123-426a-97bd-f333a0cb354d.png)

**Comment by ZekeSnider** [comment]
Can you try the [v1.5.5](https://github.com/ZekeSnider/Jared/releases/tag/v1.5.5) release? That should fix the issue for group IDs using the `;-;` format.
