### ISSUE TITLE
"Tap To Load" for OpenGraph previews

### ISSUE THREAD

**Issue by paul-brenner** [ZekeSnider/Jared#82]
When Jared sends text that ends with a link to content that has an opengraph preview it shows up with "Click/Tap to load preview"
<img width="214" alt="image" src="https://github.com/ZekeSnider/Jared/assets/13038942/0bb0a244-80f2-4aa5-9161-eaac3ff53b81">

This [StackOverflow](https://stackoverflow.com/questions/50616536/remove-need-to-press-tap-to-load-preview-for-iphone-opengraph-sms-message) explains that the OpenGraph previews are actually generated on the sending device. Is that something Jared can do easily since it is running on an actual mac? 
 
If the answer is "yes, it could, but it would take some work" then no worries. I just appreciate that you made this tool and open sourced it in the first place. Thanks!

**Comment by ZekeSnider** [comment]
Underneath the hood Jared uses the AppleScript interface for iMessage, which as far as I know doesn't support this unfortunately. If there is a way accomplish this, would be happy to add it.

https://apple.stackexchange.com/questions/458196/how-can-i-programmatically-send-a-messages-app-message-where-link-previews-work

**Comment by paul-brenner** [comment]
Ah, searching based on that turns up a lot of unanswered questions from people running into the same problem. I'll just assume for now it is impossible. Thanks!
